#!/usr/bin/env node
'use strict';

/**
 * Hadaf Venture — static site generator
 * =====================================
 * Zero dependencies. Renders the complete site into `dist/`, which is a plain
 * static folder deployable to any host with no server runtime (Spec 7.1, 12).
 *
 *   node build.js          build into dist/
 *   node build.js --clean  wipe dist/ first
 *
 * The generator exists for one reason: 16 page templates and 38 products must
 * share one design system. Every page is composed from src/lib/layout.js and
 * src/lib/components.js, and every product page and grid renders from
 * src/data/products.json — so nothing drifts.
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'src');
const DIST = path.join(ROOT, 'dist');

const catalog = require('./src/lib/products');
const { productImage } = require('./src/lib/images');
const { banners } = require('./src/lib/banners');
const site = require('./src/data/site.json');

const home = require('./src/pages/home');
const shop = require('./src/pages/shop');
const product = require('./src/pages/product');
const commerce = require('./src/pages/commerce');
const content = require('./src/pages/content');
const policies = require('./src/pages/policies');

/* ------------------------------------------------------------------ *
 * Small fs helpers
 * ------------------------------------------------------------------ */

let fileCount = 0;

function write(relPath, data) {
  const full = path.join(DIST, relPath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, data);
  fileCount += 1;
}

function copy(from, relTo) {
  const full = path.join(DIST, relTo);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.copyFileSync(from, full);
  fileCount += 1;
}

function copyDir(from, relTo) {
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const rel = path.posix.join(relTo, entry.name);
    if (entry.isDirectory()) copyDir(src, rel);
    else copy(src, rel);
  }
}

/* ------------------------------------------------------------------ *
 * Build
 * ------------------------------------------------------------------ */

function build() {
  const started = Date.now();

  if (process.argv.includes('--clean') && fs.existsSync(DIST)) {
    fs.rmSync(DIST, { recursive: true, force: true });
  }
  fs.mkdirSync(DIST, { recursive: true });

  /* --- 1. Static assets ------------------------------------------ */
  copyDir(path.join(SRC, 'assets'), 'assets');
  copy(path.join(SRC, 'assets', 'favicon.ico'), 'favicon.ico');

  /* --- 2. Client-side catalog ------------------------------------
     Emitted as a plain script (not fetched JSON) so cart, filtering and
     product lookups work with no network request and no CORS constraints. */
  const clientCatalog = catalog.products.map((p) => ({
    id: p.id,
    sku: p.sku,
    name: p.name,
    slug: p.slug,
    url: p.url,
    category: p.category,
    subcategory: p.subcategory,
    price: p.price,
    colorTheme: p.colorTheme,
    accentTheme: p.accentTheme,
    shortDescription: p.shortDescription,
    image: p.images[0],
    aspect: p.aspect,
    order: p.order,
    isGarment: p.isGarment,
    sizes: p.sizes || null,
    shade: p.shade || null,
    colour: p.colour || null,
    netQuantity: p.netQuantity || null,
  }));

  write(
    'assets/js/catalog.js',
    `/* Generated by build.js from src/data/products.json — do not edit by hand. */\n` +
      `window.HV_PRODUCTS = ${JSON.stringify(clientCatalog)};\n` +
      `window.HV_CONFIG = ${JSON.stringify({
        currency: site.currency,
        deliveryFee: site.deliveryFee,
        freeDeliveryThreshold: site.freeDeliveryThreshold,
        deliveryDays: site.deliveryDays,
        email: site.email,
        priceBounds: catalog.priceBounds,
      })};\n`
  );

  /* --- 3. Product imagery (Spec 3.5) ----------------------------- */
  catalog.products.forEach((p) => {
    for (let view = 1; view <= 3; view += 1) {
      write(`assets/img/products/${p.id}-${view}.svg`, productImage(p, view));
    }
  });

  /* --- 4. Brand banners ------------------------------------------ */
  Object.entries(banners).forEach(([name, svg]) => {
    write(`assets/img/brand/${name}`, svg);
  });

  /* --- 5. Pages (16 templates) ----------------------------------- */
  write('index.html', home.build()); //                        1  Homepage
  write('shop/index.html', shop.build('all')); //              2  Shop — All
  write('shop/fashion/index.html', shop.build('fashion')); //  3  Shop — Fashion
  write('shop/beauty/index.html', shop.build('beauty')); //    4  Shop — Beauty

  catalog.products.forEach((p) => {
    //                                                         5  Product detail (x38)
    write(`product/${p.slug}/index.html`, product.build(p));
  });

  write('cart/index.html', commerce.cart()); //                6  Cart
  write('checkout/index.html', commerce.checkout()); //        7  Checkout
  write('order-confirmation/index.html', commerce.confirmation()); // 8 Confirmation
  write('about/index.html', content.about()); //               9  About Us
  write('contact/index.html', content.contact()); //          10  Contact Us
  write('faq/index.html', content.faq()); //                  11  FAQ
  write('shipping-policy/index.html', policies.shipping()); //12  Shipping & Delivery
  write('returns-policy/index.html', policies.returns()); //  13  Return & Refund
  write('privacy-policy/index.html', policies.privacy()); //  14  Privacy Policy
  write('terms-conditions/index.html', policies.terms()); //  15  Terms & Conditions

  const nf = content.notFound();
  write('404.html', nf); //                                   16  404 Not Found
  // Some hosts look for /404/index.html instead of /404.html.
  write('404/index.html', nf);

  /* --- 6. SEO + host config -------------------------------------- */
  const urls = [
    '/',
    '/shop/',
    '/shop/fashion/',
    '/shop/beauty/',
    '/cart/',
    '/checkout/',
    '/about/',
    '/contact/',
    '/faq/',
    '/shipping-policy/',
    '/returns-policy/',
    '/privacy-policy/',
    '/terms-conditions/',
  ].concat(catalog.products.map((p) => p.url));

  write(
    'sitemap.xml',
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
      urls
        .map(
          (u) =>
            `  <url><loc>${site.url}${u}</loc><changefreq>weekly</changefreq><priority>${
              u === '/' ? '1.0' : u.startsWith('/product/') ? '0.7' : '0.8'
            }</priority></url>`
        )
        .join('\n') +
      `\n</urlset>\n`
  );

  write(
    'robots.txt',
    `User-agent: *\nAllow: /\nDisallow: /cart/\nDisallow: /checkout/\nDisallow: /order-confirmation/\n\nSitemap: ${site.url}/sitemap.xml\n`
  );

  // Netlify / Cloudflare Pages: serve the styled 404 for unknown paths.
  write('_redirects', `/*  /404.html  404\n`);

  // Apache / cPanel shared hosting equivalent.
  write(
    '.htaccess',
    `ErrorDocument 404 /404.html\n\n` +
      `# Serve pretty URLs without the trailing slash too (e.g. /about -> /about/)\n` +
      `<IfModule mod_rewrite.c>\n` +
      `  RewriteEngine On\n` +
      `  RewriteCond %{REQUEST_FILENAME} !-f\n` +
      `  RewriteCond %{REQUEST_FILENAME}/index.html -f\n` +
      `  RewriteRule ^(.*)$ /$1/ [R=301,L]\n` +
      `</IfModule>\n\n` +
      `<IfModule mod_deflate.c>\n` +
      `  AddOutputFilterByType DEFLATE text/html text/css application/javascript image/svg+xml\n` +
      `</IfModule>\n`
  );

  const ms = Date.now() - started;
  const pages = 16;
  console.log(
    `Hadaf Venture — build complete in ${ms}ms\n` +
      `  ${pages} page templates  ·  ${catalog.products.length + 15} HTML files\n` +
      `  ${catalog.products.length} products  ·  ${catalog.products.length * 3} product visuals\n` +
      `  ${fileCount} files written to dist/`
  );
}

build();
