#!/usr/bin/env node
'use strict';

/**
 * Hadaf Venture Trading — static site generator
 * ==============================================
 * Zero dependencies. Renders the complete site into `dist/`, which is a plain
 * static folder deployable to any host with no server runtime.
 *
 *   node build.js          build into dist/
 *   node build.js --clean  wipe dist/ first
 *
 * This is a wholesale garment catalogue, not a retail store: there is no
 * cart, checkout or payment flow. Pricing is "Price on Request" (see
 * src/lib/components.js) and conversion happens through the Wholesale
 * Enquiry form and WhatsApp, not a checkout.
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'src');
const DIST = path.join(ROOT, 'dist');

const catalog = require('./src/lib/products');
const { productImage } = require('./src/lib/images');
const { photosFor } = require('./src/lib/real-photos');
const { photoFor: brandPhotoFor } = require('./src/lib/real-banners');
const { banners } = require('./src/lib/banners');
const site = require('./src/data/site.json');

const home = require('./src/pages/home');
const catalogue = require('./src/pages/catalogue');
const product = require('./src/pages/product');
const enquiry = require('./src/pages/enquiry');
const wholesaleProcess = require('./src/pages/wholesale-process');
const content = require('./src/pages/content');
const policies = require('./src/pages/policies');

/* ------------------------------------------------------------------ *
 * Small fs helpers
 * ------------------------------------------------------------------ */

let fileCount = 0;

function write(relPath, data) {
  const full = path.join(DIST, relPath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, data);
  fileCount += 1;
}

function copy(from, relTo) {
  const full = path.join(DIST, relTo);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.copyFileSync(from, full);
  fileCount += 1;
}

function copyDir(from, relTo) {
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const rel = path.posix.join(relTo, entry.name);
    if (entry.isDirectory()) copyDir(src, rel);
    else copy(src, rel);
  }
}

/* ------------------------------------------------------------------ *
 * Build
 * ------------------------------------------------------------------ */

function build() {
  const started = Date.now();

  if (process.argv.includes('--clean') && fs.existsSync(DIST)) {
    fs.rmSync(DIST, { recursive: true, force: true });
  }
  fs.mkdirSync(DIST, { recursive: true });

  /* --- 1. Static assets ------------------------------------------ */
  copyDir(path.join(SRC, 'assets'), 'assets');
  copy(path.join(SRC, 'assets', 'favicon.ico'), 'favicon.ico');

  /* --- 2. Client-side catalog ------------------------------------
     Emitted as a plain script (not fetched JSON) so filtering and product
     lookups work with no network request and no CORS constraints. No price
     is ever included unless a real wholesalePrice has been confirmed. */
  const clientCatalog = catalog.products.map((p) => ({
    id: p.id,
    sku: p.sku,
    name: p.name,
    slug: p.slug,
    url: p.url,
    subcategory: p.subcategory,
    wholesalePrice: p.wholesalePrice || null,
    colorTheme: p.colorTheme,
    accentTheme: p.accentTheme,
    shortDescription: p.shortDescription,
    image: p.images[0],
    aspect: p.aspect,
    order: p.order,
    sizes: p.sizes || null,
    colour: p.colour || null,
  }));

  write(
    'assets/js/catalog.js',
    `/* Generated by build.js from src/data/products.json — do not edit by hand. */\n` +
      `window.HV_PRODUCTS = ${JSON.stringify(clientCatalog)};\n` +
      `window.HV_CONFIG = ${JSON.stringify({
        email: site.email,
      })};\n`
  );

  /* --- 3. Product imagery ------------------------------------------
     Real photography (src/data/product-photos/) wins per-product and is
     copied as-is; everything else still gets the generated placeholder set. */
  let realImages = 0;
  let generatedImages = 0;
  catalog.products.forEach((p) => {
    const real = photosFor(p.id);
    if (real.length) {
      real.forEach((r) => {
        copy(r.file, `assets/img/products/${p.id}-${r.view}.${r.ext}`);
        realImages += 1;
      });
    } else {
      for (let view = 1; view <= 3; view += 1) {
        write(`assets/img/products/${p.id}-${view}.svg`, productImage(p, view));
        generatedImages += 1;
      }
    }
  });

  /* --- 4. Brand banners --------------------------------------------
     Real photography (src/data/brand-photos/) wins per-key, same policy as
     product imagery — copied as-is; every other key still gets its
     generated SVG. */
  let realBanners = 0;
  let generatedBanners = 0;
  Object.entries(banners).forEach(([key, svg]) => {
    const real = brandPhotoFor(key);
    if (real) {
      copy(real.file, `assets/img/brand/${key}.${real.ext}`);
      realBanners += 1;
    } else {
      write(`assets/img/brand/${key}.svg`, svg);
      generatedBanners += 1;
    }
  });

  /* --- 5. Pages ---------------------------------------------------- */
  write('index.html', home.build()); //                              Homepage
  write('catalogue/index.html', catalogue.build()); //                Wholesale Catalogue

  catalog.products.forEach((p) => {
    //                                                                Product detail (x21)
    write(`product/${p.slug}/index.html`, product.build(p));
  });

  write('enquiry/index.html', enquiry.build()); //                    Wholesale Enquiry
  write('wholesale-process/index.html', wholesaleProcess.build()); // Wholesale Process
  write('about/index.html', content.about()); //                     About Us
  write('contact/index.html', content.contact()); //                 Contact Us
  write('faq/index.html', content.faq()); //                         FAQ
  write('delivery-payment-terms/index.html', policies.deliveryPaymentTerms()); // Delivery & Payment
  write('privacy-policy/index.html', policies.privacy()); //         Privacy Policy
  write('trade-terms/index.html', policies.tradeTerms()); //         Trade Terms & Conditions

  const nf = content.notFound();
  write('404.html', nf); //                                          404 Not Found
  // Some hosts look for /404/index.html instead of /404.html.
  write('404/index.html', nf);

  /* --- 6. SEO + host config -------------------------------------- */
  const urls = [
    '/',
    '/catalogue/',
    '/enquiry/',
    '/wholesale-process/',
    '/about/',
    '/contact/',
    '/faq/',
    '/delivery-payment-terms/',
    '/privacy-policy/',
    '/trade-terms/',
  ].concat(catalog.products.map((p) => p.url));

  write(
    'sitemap.xml',
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
      urls
        .map(
          (u) =>
            `  <url><loc>${site.url}${u}</loc><changefreq>weekly</changefreq><priority>${
              u === '/' ? '1.0' : u.startsWith('/product/') ? '0.7' : '0.8'
            }</priority></url>`
        )
        .join('\n') +
      `\n</urlset>\n`
  );

  write('robots.txt', `User-agent: *\nAllow: /\n\nSitemap: ${site.url}/sitemap.xml\n`);

  // Redirects from the old retail-era URLs (cart/checkout/shop split, old
  // policy pages) to their nearest wholesale equivalent, since this site was
  // already live — old bookmarks and search results should still land
  // somewhere sensible rather than 404.
  const redirects = [
    ['/shop/*', '/catalogue/'],
    ['/shop/', '/catalogue/'],
    ['/shop/fashion/', '/catalogue/'],
    ['/shop/beauty/', '/catalogue/'],
    ['/cart/', '/catalogue/'],
    ['/checkout/', '/catalogue/'],
    ['/order-confirmation/', '/'],
    ['/shipping-policy/', '/delivery-payment-terms/'],
    ['/returns-policy/', '/trade-terms/'],
    ['/terms-conditions/', '/trade-terms/'],
  ];

  // Netlify / Cloudflare Pages.
  write(
    '_redirects',
    redirects.map(([from, to]) => `${from}  ${to}  301`).join('\n') + `\n/*  /404.html  404\n`
  );

  // Apache / cPanel shared hosting equivalent.
  write(
    '.htaccess',
    `ErrorDocument 404 /404.html\n\n` +
      `<IfModule mod_rewrite.c>\n` +
      `  RewriteEngine On\n\n` +
      `  # Old retail-era URLs -> nearest wholesale equivalent\n` +
      redirects
        .map(([from, to]) => `  RewriteRule ^${from.replace(/^\//, '').replace(/\*$/, '.*')}$ ${to} [R=301,L]`)
        .join('\n') +
      `\n\n  # Serve pretty URLs without the trailing slash too (e.g. /about -> /about/)\n` +
      `  RewriteCond %{REQUEST_FILENAME} !-f\n` +
      `  RewriteCond %{REQUEST_FILENAME}/index.html -f\n` +
      `  RewriteRule ^(.*)$ /$1/ [R=301,L]\n` +
      `</IfModule>\n\n` +
      `<IfModule mod_deflate.c>\n` +
      `  AddOutputFilterByType DEFLATE text/html text/css application/javascript image/svg+xml\n` +
      `</IfModule>\n`
  );

  const ms = Date.now() - started;
  const productsWithPhotos = catalog.products.filter((p) => p.hasRealPhotos).length;
  console.log(
    `Hadaf Venture Trading — build complete in ${ms}ms\n` +
      `  11 page templates  ·  ${catalog.products.length + 11} HTML files\n` +
      `  ${catalog.products.length} products (${productsWithPhotos} with real photography, ${
        catalog.products.length - productsWithPhotos
      } placeholder)\n` +
      `  ${realImages} real product photos  ·  ${generatedImages} generated product visuals\n` +
      `  ${realBanners} real banners  ·  ${generatedBanners} generated banners\n` +
      `  ${fileCount} files written to dist/`
  );
}

build();
